IF EXISTS (SELECT loginname FROM master.dbo.syslogins WHERE name = '$(SECONDARY_USER)')
BEGIN
    DROP LOGIN $(SECONDARY_USER);
END

CREATE LOGIN $(SECONDARY_USER) WITH PASSWORD='$(SECONDARY_USER_PASSWORD)'; ALTER LOGIN $(SECONDARY_USER) ENABLE;
GO

Use $(DT_NAME);
GO

DROP USER $(SECONDARY_USER);

CREATE USER $(SECONDARY_USER) FOR LOGIN $(SECONDARY_USER);
EXEC sp_addrolemember N'db_owner', N'$(SECONDARY_USER)';

GO